
package program;

import com.sun.awt.AWTUtilities;
import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ludzie.Nauczyciel;

/**
 *
 * @author Mateusz
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
        setTitle("Dziennik");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RokDialog = new javax.swing.JFrame();
        TekstRoku = new javax.swing.JLabel();
        WyborRoku = new javax.swing.JComboBox();
        RokDialogCancel = new javax.swing.JButton();
        RokDialogOk = new javax.swing.JButton();
        DodajRok = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DodawanieRokWartosc = new javax.swing.JTextField();
        DodawanieWarn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UsunRok = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        UsunRokWartosc = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        UsunRokOK = new javax.swing.JButton();
        NauczycielUsuwanie = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        NauczycielUsuwanieWybor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        NauczycielUsuwanieOK = new javax.swing.JButton();
        NauczycielUsuwanieAnuluj = new javax.swing.JButton();
        NauczycieleUstawianie = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        KlasyDodawanieOkno = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DodawanieWychowawcyWybor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        DodajKlaseAnuluj = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        DodawanieNumerKL = new javax.swing.JComboBox();
        DodawanieKlasyZnak = new javax.swing.JComboBox();
        DodawanieKlasyWarn = new javax.swing.JLabel();
        KlasyUsuwanieOkno = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        UsuwanieKlasyOK = new javax.swing.JButton();
        UsuwanieKlasyAnuluj = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        UsuwanieKlasyWybor = new javax.swing.JComboBox();
        KartyProgramu = new javax.swing.JTabbedPane();
        NauczycieleTab = new javax.swing.JPanel();
        TabelaNauczycieli = new javax.swing.JScrollPane();
        NauczycieleTabela = new javax.swing.JTable();
        NauczycieleDodaj = new javax.swing.JButton();
        NauczycieleUsun = new javax.swing.JButton();
        NauczycieleUstaw = new javax.swing.JButton();
        KlasyTab = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelaKlas = new javax.swing.JTable();
        KlasyDodaj = new javax.swing.JButton();
        KlasyUsun = new javax.swing.JButton();
        KlasyUstaw = new javax.swing.JButton();
        PrzedmiotyTab = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        UczniowieTab = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        program = new javax.swing.JMenu();
        PrzykladoweDaneMenu = new javax.swing.JCheckBoxMenuItem();
        Odswież = new javax.swing.JMenuItem();
        RokMenu = new javax.swing.JMenu();
        UstawianieRokuMenu = new javax.swing.JMenuItem();
        DodawanieRokuMenu = new javax.swing.JMenuItem();
        UsuwanieRokuMenu = new javax.swing.JMenuItem();

        RokDialog.setTitle("Wybór roku");
        RokDialog.setMinimumSize(new java.awt.Dimension(350, 200));

        TekstRoku.setText("Wybierz obecny rok:");

        WyborRoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WyborRokuActionPerformed(evt);
            }
        });

        RokDialogCancel.setText("Cancel");
        RokDialogCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RokDialogCancelActionPerformed(evt);
            }
        });

        RokDialogOk.setText("OK");
        RokDialogOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RokDialogOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RokDialogLayout = new javax.swing.GroupLayout(RokDialog.getContentPane());
        RokDialog.getContentPane().setLayout(RokDialogLayout);
        RokDialogLayout.setHorizontalGroup(
            RokDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RokDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RokDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TekstRoku)
                    .addGroup(RokDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(RokDialogCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(RokDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RokDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(WyborRoku, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RokDialogLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(RokDialogOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        RokDialogLayout.setVerticalGroup(
            RokDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RokDialogLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(RokDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TekstRoku)
                    .addComponent(WyborRoku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(RokDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RokDialogCancel)
                    .addComponent(RokDialogOk))
                .addGap(31, 31, 31))
        );

        DodajRok.setTitle("Dodawanie Roku");
        DodajRok.setLocationByPlatform(true);
        DodajRok.setMinimumSize(new java.awt.Dimension(350, 200));

        jLabel1.setText("Podaj rok w którym zaczyna się rok szkolny do utworzenia:");

        DodawanieRokWartosc.setText("2014");
        DodawanieRokWartosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodawanieRokWartoscActionPerformed(evt);
            }
        });

        DodawanieWarn.setForeground(new java.awt.Color(255, 0, 0));
        DodawanieWarn.setText("Podana wartość musi być liczbą! (2000-3000)");

        jButton1.setText("Anuluj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Dodaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DodawanieWarn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(DodawanieRokWartosc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 34, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DodawanieRokWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DodawanieWarn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout DodajRokLayout = new javax.swing.GroupLayout(DodajRok.getContentPane());
        DodajRok.getContentPane().setLayout(DodajRokLayout);
        DodajRokLayout.setHorizontalGroup(
            DodajRokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DodajRokLayout.setVerticalGroup(
            DodajRokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UsunRok.setTitle("Usuwanie roku");
        UsunRok.setLocationByPlatform(true);
        UsunRok.setMinimumSize(new java.awt.Dimension(350, 200));

        UsunRokWartosc.setEditable(true);
        UsunRokWartosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunRokWartoscActionPerformed(evt);
            }
        });

        jLabel2.setText("Który rok chcesz usunąć:");

        jButton3.setText("Anuluj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        UsunRokOK.setText("Usuń");
        UsunRokOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunRokOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(UsunRokWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UsunRokOK)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UsunRokWartosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(UsunRokOK))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout UsunRokLayout = new javax.swing.GroupLayout(UsunRok.getContentPane());
        UsunRok.getContentPane().setLayout(UsunRokLayout);
        UsunRokLayout.setHorizontalGroup(
            UsunRokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UsunRokLayout.setVerticalGroup(
            UsunRokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NauczycielUsuwanie.setLocationByPlatform(true);
        NauczycielUsuwanie.setMinimumSize(new java.awt.Dimension(350, 200));

        jLabel3.setText("Którego nauczyciela usunąć?");

        NauczycielUsuwanieOK.setText("Usuń");
        NauczycielUsuwanieOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NauczycielUsuwanieOKActionPerformed(evt);
            }
        });

        NauczycielUsuwanieAnuluj.setText("Anuluj");
        NauczycielUsuwanieAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NauczycielUsuwanieAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(NauczycielUsuwanieAnuluj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NauczycielUsuwanieOK))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(NauczycielUsuwanieWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NauczycielUsuwanieWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NauczycielUsuwanieOK)
                    .addComponent(NauczycielUsuwanieAnuluj))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout NauczycielUsuwanieLayout = new javax.swing.GroupLayout(NauczycielUsuwanie.getContentPane());
        NauczycielUsuwanie.getContentPane().setLayout(NauczycielUsuwanieLayout);
        NauczycielUsuwanieLayout.setHorizontalGroup(
            NauczycielUsuwanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NauczycielUsuwanieLayout.setVerticalGroup(
            NauczycielUsuwanieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NauczycieleUstawianie.setLocationByPlatform(true);
        NauczycieleUstawianie.setMinimumSize(new java.awt.Dimension(350, 200));

        jLabel8.setText("Wybierz nauczyciela do edycji: ");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NauczycieleUstawianieLayout = new javax.swing.GroupLayout(NauczycieleUstawianie.getContentPane());
        NauczycieleUstawianie.getContentPane().setLayout(NauczycieleUstawianieLayout);
        NauczycieleUstawianieLayout.setHorizontalGroup(
            NauczycieleUstawianieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NauczycieleUstawianieLayout.setVerticalGroup(
            NauczycieleUstawianieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        KlasyDodawanieOkno.setMinimumSize(new java.awt.Dimension(400, 250));

        jLabel4.setText("Wybierz nr. klasy");

        jLabel5.setText("Wybierz literę");

        DodawanieWychowawcyWybor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodawanieWychowawcyWyborActionPerformed(evt);
            }
        });

        jLabel7.setText("Wybierz wychowawcę");

        DodajKlaseAnuluj.setText("Anuluj");
        DodajKlaseAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajKlaseAnulujActionPerformed(evt);
            }
        });

        jButton5.setText("Dodaj");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        DodawanieNumerKL.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        DodawanieKlasyZnak.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" }));
        DodawanieKlasyZnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodawanieKlasyZnakActionPerformed(evt);
            }
        });

        DodawanieKlasyWarn.setForeground(new java.awt.Color(255, 0, 0));
        DodawanieKlasyWarn.setText("Źle wybrane dane!");

        javax.swing.GroupLayout KlasyDodawanieOknoLayout = new javax.swing.GroupLayout(KlasyDodawanieOkno.getContentPane());
        KlasyDodawanieOkno.getContentPane().setLayout(KlasyDodawanieOknoLayout);
        KlasyDodawanieOknoLayout.setHorizontalGroup(
            KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KlasyDodawanieOknoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KlasyDodawanieOknoLayout.createSequentialGroup()
                        .addComponent(DodawanieKlasyWarn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(KlasyDodawanieOknoLayout.createSequentialGroup()
                        .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KlasyDodawanieOknoLayout.createSequentialGroup()
                                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DodawanieWychowawcyWybor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DodawanieNumerKL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DodawanieKlasyZnak, 0, 122, Short.MAX_VALUE)))
                            .addGroup(KlasyDodawanieOknoLayout.createSequentialGroup()
                                .addComponent(DodajKlaseAnuluj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5)))
                        .addGap(16, 16, 16))))
        );
        KlasyDodawanieOknoLayout.setVerticalGroup(
            KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KlasyDodawanieOknoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DodawanieNumerKL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DodawanieKlasyZnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DodawanieWychowawcyWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DodawanieKlasyWarn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(KlasyDodawanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DodajKlaseAnuluj)
                    .addComponent(jButton5))
                .addGap(20, 20, 20))
        );

        KlasyUsuwanieOkno.setMinimumSize(new java.awt.Dimension(350, 200));

        UsuwanieKlasyOK.setText("Usuń");
        UsuwanieKlasyOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuwanieKlasyOKActionPerformed(evt);
            }
        });

        UsuwanieKlasyAnuluj.setText("Anuluj");
        UsuwanieKlasyAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuwanieKlasyAnulujActionPerformed(evt);
            }
        });

        jLabel9.setText("Którą klasę chcesz usunąc:");

        UsuwanieKlasyWybor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuwanieKlasyWyborActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(UsuwanieKlasyAnuluj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UsuwanieKlasyOK))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(UsuwanieKlasyWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(UsuwanieKlasyWybor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuwanieKlasyOK)
                    .addComponent(UsuwanieKlasyAnuluj))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout KlasyUsuwanieOknoLayout = new javax.swing.GroupLayout(KlasyUsuwanieOkno.getContentPane());
        KlasyUsuwanieOkno.getContentPane().setLayout(KlasyUsuwanieOknoLayout);
        KlasyUsuwanieOknoLayout.setHorizontalGroup(
            KlasyUsuwanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KlasyUsuwanieOknoLayout.setVerticalGroup(
            KlasyUsuwanieOknoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        KartyProgramu.setPreferredSize(new java.awt.Dimension(600, 500));

        NauczycieleTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Imie", "Nazwisko", "Dodatkowe dane"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaNauczycieli.setViewportView(NauczycieleTabela);

        NauczycieleDodaj.setText("Dodaj");
        NauczycieleDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NauczycieleDodajActionPerformed(evt);
            }
        });

        NauczycieleUsun.setText("Usuń");
        NauczycieleUsun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NauczycieleUsunItemStateChanged(evt);
            }
        });
        NauczycieleUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NauczycieleUsunActionPerformed(evt);
            }
        });

        NauczycieleUstaw.setText("Ustaw dodatkowe dane");
        NauczycieleUstaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NauczycieleUstawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NauczycieleTabLayout = new javax.swing.GroupLayout(NauczycieleTab);
        NauczycieleTab.setLayout(NauczycieleTabLayout);
        NauczycieleTabLayout.setHorizontalGroup(
            NauczycieleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NauczycieleTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NauczycieleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabelaNauczycieli, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NauczycieleTabLayout.createSequentialGroup()
                        .addComponent(NauczycieleDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NauczycieleUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NauczycieleUstaw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NauczycieleTabLayout.setVerticalGroup(
            NauczycieleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NauczycieleTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NauczycieleTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NauczycieleDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NauczycieleUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NauczycieleUstaw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabelaNauczycieli, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        KartyProgramu.addTab("Nauczyciele", NauczycieleTab);

        TabelaKlas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Znak", "Wychowawca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TabelaKlas);

        KlasyDodaj.setText("Dodaj");
        KlasyDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlasyDodajActionPerformed(evt);
            }
        });

        KlasyUsun.setText("Usuń");
        KlasyUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlasyUsunActionPerformed(evt);
            }
        });

        KlasyUstaw.setText("Ustaw wychowawcę");

        javax.swing.GroupLayout KlasyTabLayout = new javax.swing.GroupLayout(KlasyTab);
        KlasyTab.setLayout(KlasyTabLayout);
        KlasyTabLayout.setHorizontalGroup(
            KlasyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KlasyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KlasyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KlasyTabLayout.createSequentialGroup()
                        .addComponent(KlasyDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KlasyUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KlasyUstaw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        KlasyTabLayout.setVerticalGroup(
            KlasyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KlasyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KlasyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KlasyDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KlasyUsun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KlasyUstaw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        KartyProgramu.addTab("Klasy", KlasyTab);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Znak", "Nauczyciel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable6);

        jButton16.setText("Dodaj");

        jButton17.setText("Usuń");

        jButton18.setText("Ustaw nauczyciela");

        javax.swing.GroupLayout PrzedmiotyTabLayout = new javax.swing.GroupLayout(PrzedmiotyTab);
        PrzedmiotyTab.setLayout(PrzedmiotyTabLayout);
        PrzedmiotyTabLayout.setHorizontalGroup(
            PrzedmiotyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrzedmiotyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrzedmiotyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrzedmiotyTabLayout.createSequentialGroup()
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PrzedmiotyTabLayout.setVerticalGroup(
            PrzedmiotyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrzedmiotyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrzedmiotyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        KartyProgramu.addTab("Przedmioty", PrzedmiotyTab);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Znak", "Dodatkowe dane"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        jButton19.setText("Dodaj");

        jButton20.setText("Usuń");

        jButton21.setText("Ustaw dodatkowe dane");

        javax.swing.GroupLayout UczniowieTabLayout = new javax.swing.GroupLayout(UczniowieTab);
        UczniowieTab.setLayout(UczniowieTabLayout);
        UczniowieTabLayout.setHorizontalGroup(
            UczniowieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UczniowieTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UczniowieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UczniowieTabLayout.createSequentialGroup()
                        .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UczniowieTabLayout.setVerticalGroup(
            UczniowieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UczniowieTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UczniowieTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        KartyProgramu.addTab("Uczniowie", UczniowieTab);

        program.setText("Program");
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });

        PrzykladoweDaneMenu.setText("Załaduj przykładowe dane");
        PrzykladoweDaneMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrzykladoweDaneMenuActionPerformed(evt);
            }
        });
        program.add(PrzykladoweDaneMenu);

        Odswież.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        Odswież.setText("Odśwież tabele");
        Odswież.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdswieżActionPerformed(evt);
            }
        });
        program.add(Odswież);

        jMenuBar1.add(program);

        RokMenu.setText("Rok szkolny");
        RokMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RokMenuActionPerformed(evt);
            }
        });

        UstawianieRokuMenu.setText("Ustaw rok");
        UstawianieRokuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawianieRokuMenuActionPerformed(evt);
            }
        });
        RokMenu.add(UstawianieRokuMenu);

        DodawanieRokuMenu.setText("Dodaj rok");
        DodawanieRokuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodawanieRokuMenuActionPerformed(evt);
            }
        });
        RokMenu.add(DodawanieRokuMenu);

        UsuwanieRokuMenu.setText("Usun rok");
        UsuwanieRokuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuwanieRokuMenuActionPerformed(evt);
            }
        });
        RokMenu.add(UsuwanieRokuMenu);

        jMenuBar1.add(RokMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KartyProgramu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KartyProgramu, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrzykladoweDaneMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrzykladoweDaneMenuActionPerformed

            dziennik.zaladujPrzykladoweDane();
            PrzykladoweDaneMenu.setSelected(true);
            PrzykladoweDaneMenu.setEnabled(false);
                
        OdswieżActionPerformed(evt);
    }//GEN-LAST:event_PrzykladoweDaneMenuActionPerformed

    private void NauczycieleUstawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NauczycieleUstawActionPerformed

        NauczycieleUstawianie.setVisible(true);
        
        //TODO dokończyć to
        
    }//GEN-LAST:event_NauczycieleUstawActionPerformed

    private void NauczycieleDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NauczycieleDodajActionPerformed

        String imie =   JOptionPane.showInputDialog(this, "Podaj imię nowego nauczyciela:");
        String nazwisko =   JOptionPane.showInputDialog(this, "Podaj nazwisko nowego nauczyciela:");
        
        if(imie != null && nazwisko!= null){
        
            Nauczyciel nowy = new Nauczyciel(imie, nazwisko);
            
            dziennik.addNauczyciel(nowy);
            
            DefaultTableModel tabela = (DefaultTableModel) NauczycieleTabela.getModel();
            
            tabela.addRow(new Object [] {nowy.getIdentyfikator(),nowy.getImie() , nowy.getNazwisko() } );
        
        }
    }//GEN-LAST:event_NauczycieleDodajActionPerformed

    private void OdswieżActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdswieżActionPerformed
        
     odswiezTabeleNauczycieli();
     odswierzTabeleKlas();
    }//GEN-LAST:event_OdswieżActionPerformed

    private void odswiezTabeleNauczycieli() {
    
        DefaultTableModel tabela = (DefaultTableModel) NauczycieleTabela.getModel();

        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }

        Nauczyciel[] nauczyciele = dziennik.printNauczyciele();

        for (Nauczyciel n : nauczyciele) {
            tabela.addRow(new Object[]{n.getIdentyfikator(), n.getImie(), n.getNazwisko()});
        }
    }
    
    private void odswierzTabeleKlas() {
        DefaultTableModel tabela = (DefaultTableModel) TabelaKlas.getModel();

        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }

        Klasa[] klasy = dziennik.printWszystkieKlasy();

        for (Klasa k : klasy) {
            Nauczyciel nauczyciel = dziennik.getNauczyciel(k.getIdWychowawcy());
            tabela.addRow(new Object[]{k.getNumerKlasy(), k.getZnakKlasy(), nauczyciel});
        }
    }
    
    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed

        // TODO add your handling code here:
     

    }//GEN-LAST:event_programActionPerformed

    private void KlasyDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlasyDodajActionPerformed

        KlasyDodawanieOkno.setVisible(true);
        DodawanieWychowawcyWybor.removeAllItems();
        DodawanieKlasyWarn.setVisible(false);
        
        
        Nauczyciel [] lista = dziennik.printNauczyciele();
        
        if (lista.length > 0) {
            DodawanieWychowawcyWybor.setEnabled(true);
            for (Nauczyciel n : lista) {
                DodawanieWychowawcyWybor.addItem(n);
            }
        } else {
            DodawanieWychowawcyWybor.setEnabled(false);
        }
            }//GEN-LAST:event_KlasyDodajActionPerformed

    private void RokMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RokMenuActionPerformed

       
    }//GEN-LAST:event_RokMenuActionPerformed

    private void UstawianieRokuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawianieRokuMenuActionPerformed
        Object[] tabela = dziennik.WszystkieRocznikitoArray();
        
        WyborRoku.removeAllItems();
        
        for (Object o : tabela) 
            WyborRoku.addItem(o);
        
        RokDialog.setVisible(true);
        
    }//GEN-LAST:event_UstawianieRokuMenuActionPerformed

    private void WyborRokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WyborRokuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WyborRokuActionPerformed

    private void RokDialogOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RokDialogOkActionPerformed
        
        RokDialog.setVisible(false);
        
        Object ob = WyborRoku.getSelectedItem();
        
        String napis = ob.toString().substring(0, 4);
        int rok = Integer.parseInt(napis);

        dziennik.setObecnyRokSzkolnyNa(rok);
    }//GEN-LAST:event_RokDialogOkActionPerformed

    private void RokDialogCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RokDialogCancelActionPerformed
        RokDialog.setVisible(false);
    }//GEN-LAST:event_RokDialogCancelActionPerformed

    private void DodawanieRokuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodawanieRokuMenuActionPerformed

        DodawanieWarn.setVisible(false);
        
        DodajRok.setVisible(true);
        
    }//GEN-LAST:event_DodawanieRokuMenuActionPerformed

    private void DodawanieRokWartoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodawanieRokWartoscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DodawanieRokWartoscActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String text = DodawanieRokWartosc.getText();
        int rok = -1;
        if(text != null){
            try{
            rok = Integer.parseInt(text);
            }
            catch(Throwable e){
                DodawanieWarn.setVisible(true);
            }
            
            if( rok >= 2000 && rok <= 3000){
                dziennik.addRocznik(rok);
                DodajRok.setVisible(false);
            }
            else
            DodawanieWarn.setVisible(true);
        }
        else
            DodawanieWarn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DodajRok.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        UsunRok.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UsuwanieRokuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuwanieRokuMenuActionPerformed
        
        Object[] tabela = dziennik.WszystkieRocznikitoArray();
        
        UsunRokWartosc.removeAllItems();
        
        for (Object o : tabela) {
            UsunRokWartosc.addItem(o);
        }
        UsunRok.setVisible(true);
        
    }//GEN-LAST:event_UsuwanieRokuMenuActionPerformed

    private void UsunRokOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunRokOKActionPerformed

        UsunRok.setVisible(false);

        Object ob = UsunRokWartosc.getSelectedItem();
        
        String napis = ob.toString().substring(0, 4);
        int rok = Integer.parseInt(napis);
        
        dziennik.removeRokSzkolny(rok);
            
  
        
    }//GEN-LAST:event_UsunRokOKActionPerformed

    private void UsunRokWartoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunRokWartoscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsunRokWartoscActionPerformed

    private void NauczycieleUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NauczycieleUsunActionPerformed

        
        Nauczyciel [] lista = dziennik.printNauczyciele();
        NauczycielUsuwanieWybor.removeAllItems();
        
        for(Nauczyciel n : lista){
            NauczycielUsuwanieWybor.addItem(n);
        }
        
        if (lista.length >0 )
            NauczycielUsuwanie.setVisible(true);

    }//GEN-LAST:event_NauczycieleUsunActionPerformed

    private void NauczycielUsuwanieAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NauczycielUsuwanieAnulujActionPerformed

        NauczycielUsuwanie.setVisible(false);
    }//GEN-LAST:event_NauczycielUsuwanieAnulujActionPerformed

    private void NauczycielUsuwanieOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NauczycielUsuwanieOKActionPerformed

        NauczycielUsuwanie.setVisible(false);
        
        int id=0;
        
        int indeksWybranego = NauczycielUsuwanieWybor.getSelectedIndex();
        Nauczyciel [] lista = dziennik.printNauczyciele();
        id = lista[indeksWybranego].getIdentyfikator();
        
        dziennik.removeNauczyciel(id);
        OdswieżActionPerformed(evt);
        
    }//GEN-LAST:event_NauczycielUsuwanieOKActionPerformed

    private void NauczycieleUsunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NauczycieleUsunItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_NauczycieleUsunItemStateChanged

    private void DodajKlaseAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajKlaseAnulujActionPerformed

        KlasyDodawanieOkno.setVisible(false);
    }//GEN-LAST:event_DodajKlaseAnulujActionPerformed

    private void DodawanieWychowawcyWyborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodawanieWychowawcyWyborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DodawanieWychowawcyWyborActionPerformed

    private void DodawanieKlasyZnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodawanieKlasyZnakActionPerformed

    }//GEN-LAST:event_DodawanieKlasyZnakActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int numerKlasy,id;
        char znakKlasy;
        
        numerKlasy = DodawanieNumerKL.getSelectedIndex() + 1;
        

        
        Object ob = DodawanieKlasyZnak.getSelectedItem();
        znakKlasy = ob.toString().charAt(0);

        Nauczyciel[] lista = dziennik.printNauczyciele();
        
        if (lista.length > 0) {
            
            int indeks = DodawanieWychowawcyWybor.getSelectedIndex();
            
            id = lista[indeks].getIdentyfikator();
            Nauczyciel n = lista[indeks];
            
            if (dziennik.addKlasa(numerKlasy, znakKlasy, id)) {
                
                DefaultTableModel tabela = (DefaultTableModel) TabelaKlas.getModel();
                tabela.addRow(new Object[]{numerKlasy, znakKlasy, n});
                KlasyDodawanieOkno.setVisible(false);
            } else {
                DodawanieKlasyWarn.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void KlasyUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlasyUsunActionPerformed
        Klasa[] lista = dziennik.printWszystkieKlasy();
        
        
        if(lista.length > 0){
            KlasyUsuwanieOkno.setVisible(true);
            UsuwanieKlasyWybor.removeAllItems();
            
            for (Klasa k : lista)
                UsuwanieKlasyWybor.addItem(k);
        }
        
    }//GEN-LAST:event_KlasyUsunActionPerformed

    private void UsuwanieKlasyAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuwanieKlasyAnulujActionPerformed
        KlasyUsuwanieOkno.setVisible(false);
    }//GEN-LAST:event_UsuwanieKlasyAnulujActionPerformed

    private void UsuwanieKlasyWyborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuwanieKlasyWyborActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuwanieKlasyWyborActionPerformed

    private void UsuwanieKlasyOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuwanieKlasyOKActionPerformed
        KlasyUsuwanieOkno.setVisible(false);
        
        int wybranyIndeks = UsuwanieKlasyWybor.getSelectedIndex();
        Klasa[] lista = dziennik.printWszystkieKlasy();
        
        Klasa k = lista[wybranyIndeks];
        
        dziennik.removeKlasa(k.getNumerKlasy(), k.getZnakKlasy());
        
        odswierzTabeleKlas();
    }//GEN-LAST:event_UsuwanieKlasyOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
            
        });
    }
    
    private static Dziennik dziennik = new Dziennik();
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajKlaseAnuluj;
    private javax.swing.JFrame DodajRok;
    private javax.swing.JLabel DodawanieKlasyWarn;
    private javax.swing.JComboBox DodawanieKlasyZnak;
    private javax.swing.JComboBox DodawanieNumerKL;
    private javax.swing.JTextField DodawanieRokWartosc;
    private javax.swing.JMenuItem DodawanieRokuMenu;
    private javax.swing.JLabel DodawanieWarn;
    private javax.swing.JComboBox DodawanieWychowawcyWybor;
    private javax.swing.JTabbedPane KartyProgramu;
    private javax.swing.JButton KlasyDodaj;
    private javax.swing.JFrame KlasyDodawanieOkno;
    private javax.swing.JPanel KlasyTab;
    private javax.swing.JButton KlasyUstaw;
    private javax.swing.JButton KlasyUsun;
    private javax.swing.JFrame KlasyUsuwanieOkno;
    private javax.swing.JFrame NauczycielUsuwanie;
    private javax.swing.JButton NauczycielUsuwanieAnuluj;
    private javax.swing.JButton NauczycielUsuwanieOK;
    private javax.swing.JComboBox NauczycielUsuwanieWybor;
    private javax.swing.JButton NauczycieleDodaj;
    private javax.swing.JPanel NauczycieleTab;
    private javax.swing.JTable NauczycieleTabela;
    private javax.swing.JButton NauczycieleUstaw;
    private javax.swing.JFrame NauczycieleUstawianie;
    private javax.swing.JButton NauczycieleUsun;
    private javax.swing.JMenuItem Odswież;
    private javax.swing.JPanel PrzedmiotyTab;
    private javax.swing.JCheckBoxMenuItem PrzykladoweDaneMenu;
    private javax.swing.JFrame RokDialog;
    private javax.swing.JButton RokDialogCancel;
    private javax.swing.JButton RokDialogOk;
    private javax.swing.JMenu RokMenu;
    private javax.swing.JTable TabelaKlas;
    private javax.swing.JScrollPane TabelaNauczycieli;
    private javax.swing.JLabel TekstRoku;
    private javax.swing.JPanel UczniowieTab;
    private javax.swing.JMenuItem UstawianieRokuMenu;
    private javax.swing.JFrame UsunRok;
    private javax.swing.JButton UsunRokOK;
    private javax.swing.JComboBox UsunRokWartosc;
    private javax.swing.JButton UsuwanieKlasyAnuluj;
    private javax.swing.JButton UsuwanieKlasyOK;
    private javax.swing.JComboBox UsuwanieKlasyWybor;
    private javax.swing.JMenuItem UsuwanieRokuMenu;
    private javax.swing.JComboBox WyborRoku;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JMenu program;
    // End of variables declaration//GEN-END:variables
}
